// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_StartScreen
void ui_StartScreen_screen_init(void);
extern lv_obj_t * ui_StartScreen;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_TimeDisplay
void ui_TimeDisplay_screen_init(void);
extern lv_obj_t * ui_TimeDisplay;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_ImageCapture
void ui_ImageCapture_screen_init(void);
extern lv_obj_t * ui_ImageCapture;
extern lv_obj_t * ui_CaptureImage;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_409193941);    // assets/mnme logo (1).png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
