// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_ImageCapture_screen_init(void)
{
    ui_ImageCapture = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ImageCapture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CaptureImage = lv_btn_create(ui_ImageCapture);
    lv_obj_set_width(ui_CaptureImage, 50);
    lv_obj_set_height(ui_CaptureImage, 50);
    lv_obj_set_align(ui_CaptureImage, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_CaptureImage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CaptureImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
